---
output:
  flexdashboard::flex_dashboard:
    logo: logo.png
    favicon: logo.png
    orientation: rows
    vertical_layout: fill
    theme: paper
    source_code: "https://github.com/jimhester/tidyversedashboard"
params:
  start: 
    label: Start date of report
    value: !r lubridate::today() - lubridate::ddays(30)
    input: date
  org:
    label: GitHub organization
    value: lockedata
    input: text
---

```{r setup, include = FALSE}
library(flexdashboard)
library(gh)
library(jsonlite)
library(lubridate)
library(dplyr)
library(purrr)
library(tibble)
library(codetools) # there was a weird error on connect that needed this
library(DT)
library(tidyversedashboard)
library(tidyr)
library(sparkline)
library(ggplot2)
on_macos <- tolower(Sys.info()[["sysname"]]) == "darwin"
gh_colors <- list(
  green = "#2cbe4e",
  red = "#CB2434",
  purple = "#6f42c1")
start <- params$start
duration <- format(today() - start, format = "%d")
org <- scan(text = params$org, what = "character", sep = ",", strip.white = TRUE, quiet = TRUE)
tidyversedashboard::get_org_logo(org)

```

---
title: "`r paste0(tidyversedashboard::get_org_name(org), "'s packages dashboard")`"
---


```{r pr_stats, include=FALSE, cache = on_macos}
options(repos = c(CRAN='https://cloud.r-project.org'))

```

```{r repo_stats, include = FALSE, cache = on_macos}
repo_data <- map(org, org_data)

repo_summary <- map_dfr(repo_data, "summary")
issues <- map_dfr(repo_data, "issues")
```


Repository summary
=====================================

```{r repo_summary, cache = on_macos}
summary_table <- repo_summary %>%
  rename("package" = "repo") %>%
  mutate(
    weekly_downloads = num_downloads(.$package, "last-week"),
    maintainer = desc_maintainer(description),
    reverse_deps = reverse_dependencies(package),
    dev_deps = desc_dev_deps(description),
    travis_status = travis_status_badge(owner, package),
    appveyor_status = appveyor_status_badge(owner, package),
    activity = map2(owner, package, weekly_commits)) %>%
  select(owner, package, maintainer, status, watchers, reverse_deps, weekly_downloads, open_issues, prs, p1, everything(), -description) %>%
  rename(!!emo::ji("+1") := p1)
```

```{r}
# A custom datatable with a sparkline column
dt <- sparkline_table(
  summary_table,
  sparkline_column = which(colnames(summary_table) == "activity"),
  colnames = c("52 week conmmit activity" = "activity"))
dt
```

Open issues
=====================================
```{r issue_summary}
substitute_emoji <- function(x) {
  m <- gregexpr(":[^[:space:]]+:", x)

  regmatches(x, m) <- lapply(regmatches(x, m), function(xx) map_chr(gsub(":", "", xx), emo::ji))
  x
}

# linkify the titles, and replace emoji
issue_table <- mutate(issues,
  title = glue::glue('<a rel="noopener" target="_blank" href="https://github.com/{owner}/{repo}/issues/{issue}">{title}</a>'),
  labels = substitute_emoji(map_chr(labels, paste, collapse = ", "))) %>%
  rename(!!emo::ji("+1") := p1)

data_table(issue_table)
```

